config/routes.php
<?php
  use Cake\Routing\Route\DashedRoute;
  use Cake\Routing\Router;

  /**
   * Routes for the admin dashboard
   */
  Router::plugin('Admiral/Blog',['path' => '/admin'],function ($routes) {
    $routes->get('/blog', ['controller' => 'Blog', 'action' => 'index']);
    $routes->get('/blog/add', ['controller' => 'Blog', 'action' => 'add']);
    $routes->connect('/blog/edit/:id',['controller' => 'Blog', 'action' => 'edit'])
      ->setPass(['id']);

    $routes->fallbacks(DashedRoute::class);
  });

src/Model/Table/ArticlesRevisionsTable.php
<?php
namespace Admiral\Blog\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * ArticlesRevisions Model
 *
 * @property \Admiral\Blog\Model\Table\ArticlesTable&\Cake\ORM\Association\BelongsTo $Articles
 *
 * @method \Admiral\Blog\Model\Entity\ArticlesRevision get($primaryKey, $options = [])
 * @method \Admiral\Blog\Model\Entity\ArticlesRevision newEntity($data = null, array $options = [])
 * @method \Admiral\Blog\Model\Entity\ArticlesRevision[] newEntities(array $data, array $options = [])
 * @method \Admiral\Blog\Model\Entity\ArticlesRevision|false save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \Admiral\Blog\Model\Entity\ArticlesRevision saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \Admiral\Blog\Model\Entity\ArticlesRevision patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \Admiral\Blog\Model\Entity\ArticlesRevision[] patchEntities($entities, array $data, array $options = [])
 * @method \Admiral\Blog\Model\Entity\ArticlesRevision findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class ArticlesRevisionsTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('articles_revisions');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Articles', [
            'foreignKey' => 'article_id',
            'joinType' => 'INNER',
            'className' => 'Admiral/Blog.Articles',
        ]);

        $this->belongsTo('Authors', [
          'foreignKey' => 'author_id',
          'joinType' => 'LEFT',
          'className' => 'Admiral/Admiral.Users',
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmptyString('id', null, 'create');

        $validator
            ->scalar('revision')
            ->maxLength('revision', 255)
            ->requirePresence('revision', 'create')
            ->notEmptyString('revision');

        $validator
            ->integer('published')
            ->notEmptyString('published');

        $validator
            ->scalar('thumbnail')
            ->maxLength('thumbnail', 255)
            ->allowEmptyString('thumbnail');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['article_id'], 'Articles'));

        return $rules;
    }
}

src/Model/Table/ArticlesTable.php
<?php
namespace Admiral\Blog\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Articles Model
 *
 * @property \Admiral\Admiral\Model\Table\UsersTable&\Cake\ORM\Association\BelongsTo $Users
 * @property &\Cake\ORM\Association\HasMany $ArticlesRevisions
 * @property &\Cake\ORM\Association\BelongsToMany $Comments
 * @property \App\Model\Table\TagsTable&\Cake\ORM\Association\BelongsToMany $Tags
 *
 * @method \Admiral\Blog\Model\Entity\Article get($primaryKey, $options = [])
 * @method \Admiral\Blog\Model\Entity\Article newEntity($data = null, array $options = [])
 * @method \Admiral\Blog\Model\Entity\Article[] newEntities(array $data, array $options = [])
 * @method \Admiral\Blog\Model\Entity\Article|false save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \Admiral\Blog\Model\Entity\Article saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \Admiral\Blog\Model\Entity\Article patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \Admiral\Blog\Model\Entity\Article[] patchEntities($entities, array $data, array $options = [])
 * @method \Admiral\Blog\Model\Entity\Article findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class ArticlesTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('articles');
        $this->setDisplayField('title');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Users', [
            'foreignKey' => 'user_id',
            'className' => 'Admiral/Blog.Users',
        ]);
        $this->hasMany('ArticlesRevisions', [
            'foreignKey' => 'article_id',
            'className' => 'Admiral/Blog.ArticlesRevisions',
        ]);
        $this->belongsToMany('Comments', [
            'foreignKey' => 'article_id',
            'targetForeignKey' => 'comment_id',
            'joinTable' => 'articles_comments',
            'className' => 'Admiral/Blog.Comments',
        ]);
        $this->belongsToMany('Tags', [
            'foreignKey' => 'article_id',
            'targetForeignKey' => 'tag_id',
            'joinTable' => 'articles_tags',
            'className' => 'Admiral/Blog.Tags',
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmptyString('id', null, 'create');

        $validator
            ->scalar('title')
            ->maxLength('title', 255)
            ->requirePresence('title', 'create')
            ->notEmptyString('title');

        $validator
            ->scalar('slug')
            ->maxLength('slug', 255)
            ->requirePresence('slug', 'create')
            ->notEmptyString('slug')
            ->add('slug', 'unique', ['rule' => 'validateUnique', 'provider' => 'table']);

        $validator
            ->scalar('hash')
            ->requirePresence('hash', 'create')
            ->notEmptyString('hash');

        $validator
            ->integer('published')
            ->requirePresence('published', 'create')
            ->notEmptyString('published');

        $validator
            ->scalar('thumbnail')
            ->maxLength('thumbnail', 255)
            ->allowEmptyString('thumbnail');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->isUnique(['slug']));
        $rules->add($rules->existsIn(['user_id'], 'Users'));

        return $rules;
    }
}

src/Controller/BlogController.php
<?php
  namespace Admiral\Blog\Controller;

  use Admiral\Admiral\Permission;
  use Admiral\Admiral\User;

  use Cake\Core\Configure;
  use Cake\Routing\Router;
  use Cake\Filesystem\File;
  use Cake\Event\Event;

  class BlogController extends AppController {
    public function beforeFilter(Event $event) {
      $this->Auth->autoRedirect = false;
    }

    public function initialize(): void {
      parent::initialize();

      // Load the required models
      $this->loadModel('Admiral/Blog.Articles');
      $this->loadModel('Admiral/Admiral.Users');
      $this->loadModel('Admiral/Blog.ArticlesTags');
      $this->loadModel('Admiral/Blog.ArticlesRevisions');

      $this->viewBuilder()->setClassName('Admiral/Admiral.App');

      // Check whether the current action is allowed without auth
      if(!in_array($this->request->getParam('action'),$this->Auth->allowedActions)){
        // current action requires auth
        // Check whether the user is logged in or not
        if(User::get()){
          // Check whether the user is allowed to access the CMS

          if(!Permission::check('admiral.admiral.cms.access', 1)){
            // User does not have the right permission
            $this->redirect(['controller' => 'Users', 'action' => 'my_account', 'my-account']); # redirect to the general my-account page
          }
        }else{
          // User is not logged in
          // Check whether we are on the login page
          if($this->request->getParam('action') != 'login'){
            // We are not on the login page
            $redirUrl = Router::url(["controller" => $this->request->params['controller'], "action" => $this->request->params['action']]); # Build the current url for redirection
            $this->redirect(['plugin'=>null,'controller' => 'Admin', 'action' => 'login', 'redir' => $redirUrl]); # Redirect to the login page
          }
        }
      }
    }

    public function index(){
      $this->set('title', 'All Posts');

      $this->viewBuilder()->setLayout('Admiral/Admiral.admin'); # Change the layout to the admin_login layout

      // Get the blogposts from the database
      $articles = $this->Articles->find('all',['order' => ['Articles.created' => 'DESC']])->contain(['Tags','Users']);
      $this->set('articles',$articles);
    }

    public function edit($id = null) {
      // Check whether the user has the rights to be here
      // Redirect to the dashboard if not
      if(!Permission::check('admiral.blog.posts.edit', 1)){
        $this->Flash->error('You do not have the permissions to do this');
        return $this->redirect(['plugin'=>null, 'controller'=>'admin','action'=>'index']);
      }

      // Get a list of tags
      $tags = $this->Articles->Tags->find('list');

      // Get the article data
      $article = $this->Articles->findById($id)->contain([
        'Tags',
        'ArticlesRevisions' => [
          'sort' => ['ArticlesRevisions.created' => 'DESC'],
          'Authors',
        ],
      ])
      ->firstOrFail();

      // Get the article body
      $file = new File(ROOT . DS . 'blog-posts' . DS . $article->hash . '.txt');

      // Set our view variables
      $this->set('article', $article);
      $this->set('body', $file->read());
      $this->set('title', 'Editing Post: ' . $article->title);
      $this->set('tags', $tags);
      $this->set('previewUrlTemplate', Router::url('/', true) . Configure::read('Admiral.blog.previewUrl'));

      // Change the layout
      $this->viewBuilder()->setLayout('Admiral/Admiral.admin');
    }

    public function add(){
      // Check whether the user has the rights to be here
      // If not, redirect to the dashboard
      if(!Permission::check('admiral.blog.posts.edit', 1)){
        $this->Flash->error('You do not have the permissions to do this');
        return $this->redirect(['plugin'=>null, 'controller'=>'admin','action'=>'index']);
      }


      // Get the list of tags
      $tags = $this->Articles->Tags->find('list');

      // Set our view values
      $this->set('tags', $tags);
      $this->set('title', 'Add Post');

      // Change the layout
      $this->viewBuilder()->setLayout('Admiral/Admiral.admin');
    }

    public function display() {
      $user = $this->Users->findById($this->Auth->user('id'))->contain(['Roles' => ['Permissions']])->first();
      $this->set('user', $user);
    }
  }

src/Template/Blog/add.ctp
<div class="row">
  <div class="col-lg-12">
    <?= $this->Flash->render(); ?>
  </div>
</div>

<form id="add-post">
  <div class="row">
    <div class="col-lg-9">
      <div class="form-group">
        <?= $this->Form->control("title",["placeholder"=>"Post Title","label"=>false,"class"=>"form-control rounded-0"]); ?>
      </div>
      <div class="form-group">
        <?= $this->Ui->texteditor->create('', [
          'class' => 'form-control',
          'name' => 'body'
        ]); ?>
      </div>
    </div>
    <div class="col-lg-3">
      <div class="row mb-2">
        <div class="col-lg-12">
          <?= $this->Ui->card->start(); ?>
            <?= $this->Ui->card->header('Publish'); ?>
            <?= $this->Ui->card->bodystart(); ?>
              <div class="form-check">
                <input class="form-check-input" type="radio" name="published" value="1">
                <label class="form-check-label" for="published">
                  Public
                </label>
              </div>
              <div class="form-check">
                <input class="form-check-input" type="radio" name="published" value="0" checked>
                <label class="form-check-label" for="published">
                  Private
                </label>
              </div>
              <div class="form-check">
                <input class="form-check-input" type="radio" name="published" value="2">
                <label class="form-check-label" for="published">
                  Unlisted
                </label>
              </div>
              <?= $this->Form->button('Save',["type"=>"submit","class"=>"btn btn-primary rounded-0"]); ?>
            <?= $this->Ui->card->bodyend(); ?>
          <?= $this->Ui->card->end(); ?>
        </div>
      </div>
      <div class="row mb-2">
        <div class="col-lg-12">
          <?= $this->Ui->card->start(); ?>
            <?= $this->Ui->card->header('Tags'); ?>
            <?= $this->Ui->card->bodystart(); ?>
              <?php foreach($tags as $id => $title): ?>
                <div class="form-check">
                  <?= $this->Ui->checkbox->checkbox(false, [
                    'attrs' => [
                      'name' => 'tags[]',
                      'value' => h($id),
                    ]
                  ]); ?>
                  <label class="form-check-label">
                    <?= htmlentities($title); ?>
                  </label>
                </div>
              <?php endforeach; ?>
            <?= $this->Ui->card->bodyend(); ?>
          <?= $this->Ui->card->end(); ?>
        </div>
      </div>
      <div class="row mb-2">
        <div class="col-lg-12">
          <?= $this->Ui->card->start(); ?>
            <?= $this->Ui->card->header('Thumbnail'); ?>
            <?= $this->Ui->card->bodystart(); ?>
            <div class="form-group">
              <?= $this->Form->control("thumbnail",array("placeholder"=>"Post Thumbnail URL","label"=>false,"class"=>"form-control rounded-0")); ?>
              <small>
                Please enter the full URL to a thumbnail (Leave empty for no thumbnail).
              </small>
            </div>
            <?= $this->Ui->card->bodyend(); ?>
          <?= $this->Ui->card->end(); ?>
        </div>
      </div>
    </div>
  </div>
</form>

<?php \Admiral\Admiral\Asset::script('Admiral/Blog.add-post'); ?>

src/Template/Blog/edit.ctp
<div class="row">
  <div class="col-lg-12">
    <?= $this->Flash->render(); ?>
  </div>
</div>

<form id="edit-post">
  <div class="row">
    <div class="col-lg-9">
      <div class="form-group">
        <?= $this->Form->control("title",array("placeholder"=>"Post Title","label"=>false,"class"=>"form-control rounded-0","value"=>$article->title)); ?>
        <small>
          slug:
          <span class="text-muted"><?= h($article->slug); ?>
        </small>
      </div>
      <div class="form-group">
        <?= $this->Ui->texteditor->create($body, [
          'class' => 'form-control',
          'name' => 'body'
        ]); ?>
      </div>
    </div>
    <div class="col-lg-3">
      <div class="row mb-2">
        <div class="col-lg-12">
          <?= $this->Ui->card->start(); ?>
            <?= $this->Ui->card->header('Publish'); ?>
            <?= $this->Ui->card->bodystart(); ?>
              <div class="form-check">
                <input class="form-check-input" type="radio" name="published" value="1" <?php if($article->published == 1){ ?>checked<?php } ?>>
                <label class="form-check-label" for="published">
                  Public
                </label>
              </div>
              <div class="form-check">
                <input class="form-check-input" type="radio" name="published" value="0" <?php if($article->published == 0){ ?>checked<?php } ?>>
                <label class="form-check-label" for="published">
                  Private
                </label>
              </div>
              <div class="form-check">
                <input class="form-check-input" type="radio" name="published" value="2" <?php if($article->published == 2){ ?>checked<?php } ?>>
                <label class="form-check-label" for="published">
                  Unlisted
                </label>
              </div>
              <?= $this->Form->button('Save',["type"=>"submit","class"=>"btn btn-primary rounded-0"]); ?>
              <?= $this->Form->button('Preview',["class"=>"btn btn-secondary rounded-0", "data-action" => "preview"]); ?>
            <?= $this->Ui->card->bodyend(); ?>
          <?= $this->Ui->card->end(); ?>
        </div>
      </div>
      <div class="row mb-2">
        <div class="col-lg-12">
          <?= $this->Ui->card->start(); ?>
            <?= $this->Ui->card->header('Tags'); ?>
            <?= $this->Ui->card->bodystart(); ?>
              <div class="form-group" id="tags-list">
                <?php foreach($tags as $id => $title): ?>
                  <div class="form-check">
                    <?= $this->Ui->checkbox->checkbox($this->Tags->hasTag($article,$id), [
                      'attrs' => [
                        'name' => 'tags[]',
                        'value' => h($id),
                      ]
                    ]); ?>
                    <label class="form-check-label">
                      <?= h($title); ?>
                    </label>
                  </div>
                <?php endforeach; ?>
              </div>
              <div class="form-group mt-3">
                <div class="input-group mb-3">
                  <input type="text" class="form-control rounded-0" placeholder="Create tag" name="new-tag-name">
                  <button type="button" class="btn btn-success rounded-0" data-action="create-tag">
                    <i class="fas fa-plus"></i>
                  </button>
                </div>
              </div>
            <?= $this->Ui->card->bodyend(); ?>
          <?= $this->Ui->card->end(); ?>
        </div>
      </div>
      <div class="row mb-2">
        <div class="col-lg-12">
          <?= $this->Ui->card->start(); ?>
            <?= $this->Ui->card->header('Thumbnail'); ?>
            <?= $this->Ui->card->bodystart(); ?>
            <div class="form-group">
              <?= $this->Form->control("thumbnail",array("placeholder"=>"Post Thumbnail URL","label"=>false,"class"=>"form-control rounded-0","value"=>$article->thumbnail)); ?>
              <small>
                Please enter the full URL to a thumbnail (Leave empty for no thumbnail).
              </small>
            </div>
            <?= $this->Ui->card->bodyend(); ?>
          <?= $this->Ui->card->end(); ?>
        </div>
      </div>
    </div>
  </div>
  <input type="hidden" name="post-id" value="<?= h($article->id); ?>">
  <input type="hidden" name="post-last-modified" value="<?= h($article->modified); ?>">
</form>

<div class="row">
  <div class="col-lg-7">
    <?= $this->Ui->table->start(); ?>
      <?= $this->Ui->table->header(['Date', 'Status', 'Author', 'Actions']); ?>
      <?= $this->Ui->table->bodystart(); ?>
        <?php foreach($article->articles_revisions as $revision): ?>
          <?= $this->Ui->table->rowstart('revision-' . $revision->revision); ?>
            <?= $this->Ui->table->columnstart(); ?>
              <?= $revision->created; ?>
            <?= $this->Ui->table->columnend(); ?>
            <?= $this->Ui->table->columnstart(); ?>
              <?php
                switch($revision->published){
                  case -1:
                    echo 'Unlisted';
                    break;
                  case 0:
                    echo 'Private';
                    break;
                  case 1:
                    echo 'Public';
                    break;
                }
              ?>
            <?= $this->Ui->table->columnend(); ?>
            <?= $this->Ui->table->columnstart(); ?>
              <?php if(!empty($revision->author)): ?>
                <img src="<?= h($revision->author->avatar()); ?>" style="max-height: 32px; max-width: 32px;"> <?= h($revision->author->username); ?>
              <?php else: ?>
                Unknown User
              <?php endif; ?>
            <?= $this->Ui->table->columnend(); ?>
            <?= $this->Ui->table->columnstart(); ?>
              <button class="btn btn-success rounded-0" data-action="load-revision" data-revision="<?= h($revision->revision); ?>">
                <i class="fas fa-edit"></i>
              </button>
              <button class="btn btn-primary rounded-0" data-action="view-revision" data-revision="<?= h($revision->revision); ?>">
                <i class="fas fa-eye"></i>
              </button>
              <button class="btn btn-danger rounded-0" data-action="delete-revision" data-revision="<?= h($revision->revision); ?>">
                <i class="fas fa-trash-alt"></i>
              </button>
            <?= $this->Ui->table->columnend(); ?>
          <?= $this->Ui->table->rowend(); ?>
        <?php endforeach; ?>
      <?= $this->Ui->table->bodyend(); ?>
    <?= $this->Ui->table->end(); ?>
  </div>
</div>


<?php \Admiral\Admiral\Asset::script('Admiral/Blog.edit-post'); ?>
<?php \Admiral\Admiral\Asset::script('Admiral/Blog.create-tag'); ?>
<?php \Admiral\Admiral\Asset::script('Admiral/Blog.autosave'); ?>
<?php \Admiral\Admiral\Asset::script('Admiral/Blog.view-revision'); ?>
<?php \Admiral\Admiral\Asset::script('Admiral/Blog.load-revision'); ?>
<?php \Admiral\Admiral\Asset::script('Admiral/Blog.delete-revision'); ?>

<script>
  const previewUrlTemplate = `<?= h($previewUrlTemplate); ?>`;
  const articleSlug = `<?= h($article->slug); ?>`;
</script>

<script id="tag-template" type="text/x-handlebars-template">
  <div class="form-check">
    <?= $this->Ui->checkbox->checkbox(true, [
      'attrs' => [
        'name' => 'tags[]',
        'value' => '{{ id }}',
        'id' => 'checkbox-{{ id }}',
      ]
    ]); ?>
    <label class="form-check-label">
      {{ title }}
    </label>
  </div>
</script>

src/Template/Blog/index.ctp
<?php
  use Cake\I18n\Time;
?>
<?= $this->Ui->table->start(['checkall' => true]); ?>
  <?= $this->Ui->table->header([
    'Title',
    'Author' => ['width' => 2],
    'Tags' => ['width' => 2],
    'Date' => ['width' => 2],
    'View',
    'Edit',
    'Delete'
  ]); ?>
  <tbody>
    <?php foreach($articles as $article): ?>
      <?= $this->Ui->table->rowstart(); ?>
        <td><?= h($article->title); ?></td>
        <td><?= h($article->user->username);?></td>
        <td>
          <?php foreach($article->tags as $id => $tag): ?>
            <span class="badge badge-secondary rounded-0"><?= h($tag->title); ?></span>
          <?php endforeach; ?>
        </td>
        <td>
          <?php if($article->modified > $article->created): ?>
            Modified <?= h($article->modified->format("Y-m-d")); ?> at <?= h($article->modified->format("h:i:s")); ?>
          <?php else: ?>
            Created <?= h($article->created->format("Y-m-d")); ?> at <?= h($article->created->format("h:i:s")); ?>
          <?php endif; ?>
        </td>
        <td>
          <p data-placement="top" data-toggle="tooltip" title="View">
            <button class="btn btn-primary btn-xs" data-title="View" data-toggle="modal" data-target="#view" >
              <span class="far fa-eye"></span>
            </button>
          </p>
        </td>
        <td>
          <p data-placement="top" data-toggle="tooltip" title="Edit">
            <?=
              $this->Html->link(
                $this->Html->tag(
                  'button',
                  $this->Html->tag('span',null,['class'=>'far fa-edit','escape'=>false]),
                  ['escape'=>false,'class'=>'btn btn-primary btn-xs']
                ),
                ['plugin'=>'Admiral/Blog','controller'=>'blog','action'=>'edit',$article->id],
                ['escape'=>false]
              );
            ?>
          </p>
        </td>
        <td>
          <p data-placement="top" data-toggle="tooltip" title="Delete">
            <button class="btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#delete" >
              <span class="far fa-trash-alt"></span>
            </button>
          </p>
        </td>
      <?= $this->Ui->table->rowend(); ?>
    <?php endforeach; ?>
  </tbody>
  <!-- This is actually the footer -->
  <?= $this->Ui->table->header([
    'Title',
    'Author' => ['width' => 2],
    'Tags' => ['width' => 2],
    'Date' => ['width' => 2],
    'View',
    'Edit',
    'Delete'
  ]); ?>
<?= $this->Ui->table->end(); ?>

<script>
  $(function(){
    // Initialize all the tooltips
    $("[data-toggle=tooltip]").tooltip();
  });
</script>